# Generated by Django 5.2.8 on 2025-11-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('stakeholders', models.TextField()),
                ('status', models.CharField(choices=[('IN', 'In Progress'), ('CO', 'Completed'), ('HO', 'On Hold'), ('CA', 'Canceled')], max_length=2)),
            ],
        ),
    ]
